import type { ControlRoomLog, LiveSession, MigrationRecord } from "../types";

export const seedLineInboxRecords: MigrationRecord[] = [
  {
    migration_id: "mig_line_001",
    source_channel: "line",
    source_user_id: "U7f9a001",
    source_message_id: "msg_001",
    received_at: "2026-03-25T05:42:00.000Z",
    raw_text: "Hi, looking for booking tomorrow evening in Sukhumvit. Budget around 30k.",
    parsed_name: "John",
    parsed_intent: "booking",
    parsed_budget_thb: 30000,
    parsed_date: "2026-03-26",
    parsed_location: "Sukhumvit",
    confidence_score: 0.84,
    dedupe_status: "unresolved",
    linked_client_id: null,
    flags: ["missing_phone"],
    migration_status: "needs_review",
  },
  {
    migration_id: "mig_line_002",
    source_channel: "line",
    source_user_id: "U7f9a002",
    source_message_id: "msg_002",
    received_at: "2026-03-25T06:10:00.000Z",
    raw_text: "Client Alex. Wants private dinner tonight, Four Seasons, premium only.",
    parsed_name: "Alex",
    parsed_intent: "booking",
    parsed_budget_thb: 45000,
    parsed_date: "2026-03-25",
    parsed_location: "Four Seasons",
    confidence_score: 0.91,
    dedupe_status: "create_new",
    linked_client_id: null,
    flags: [],
    migration_status: "ready_to_sync",
  },
  {
    migration_id: "mig_line_003",
    source_channel: "line",
    source_user_id: "U7f9a003",
    source_message_id: "msg_003",
    received_at: "2026-03-25T06:35:00.000Z",
    raw_text: "Maybe book next week. Need more details about rates and areas.",
    parsed_name: undefined,
    parsed_intent: "inquiry",
    confidence_score: 0.63,
    dedupe_status: "unresolved",
    linked_client_id: null,
    flags: ["missing_name", "missing_budget", "missing_date"],
    migration_status: "parsed",
  },
];

export const seedLogs: ControlRoomLog[] = [
  {
    log_id: "log_001",
    scope: "immigration",
    level: "info",
    message: "Loaded LINE inbox seed records.",
    target_id: "mig_line_001",
    ts: "2026-03-25T07:00:00.000Z",
  },
  {
    log_id: "log_002",
    scope: "sync",
    level: "info",
    message: "Sync Airtable is running in mock mode.",
    target_id: "mig_line_002",
    ts: "2026-03-25T07:05:00.000Z",
  },
  {
    log_id: "log_003",
    scope: "sessions",
    level: "warn",
    message: "Live session feed is currently placeholder data.",
    ts: "2026-03-25T07:10:00.000Z",
  },
];

export const seedSessions: LiveSession[] = [
  {
    session_id: "sess_live_001",
    customer: "John D.",
    model: "Hito",
    status: "en_route",
    eta_min: 18,
    start: { x: 160, y: 460 },
    current: { x: 430, y: 320 },
    destination: { x: 690, y: 250 },
    updated_at: "2026-03-25T07:12:00.000Z",
    raw: {
      area: "Sukhumvit",
      note: "Traffic moderate",
    },
  },
  {
    session_id: "sess_live_002",
    customer: "Alex M.",
    model: "Kenji",
    status: "arrived",
    eta_min: 0,
    start: { x: 240, y: 500 },
    current: { x: 580, y: 220 },
    destination: { x: 580, y: 220 },
    updated_at: "2026-03-25T07:15:00.000Z",
    raw: {
      area: "Four Seasons",
      note: "Confirmed onsite",
    },
  },
  {
    session_id: "sess_live_003",
    customer: "K.",
    model: "Tart",
    status: "work_started",
    eta_min: 0,
    start: { x: 120, y: 560 },
    current: { x: 760, y: 180 },
    destination: { x: 760, y: 180 },
    updated_at: "2026-03-25T07:18:00.000Z",
    raw: {
      area: "Private Venue",
      note: "Session in progress",
    },
  },
];
