name = "telegram-worker"
main = "index.js"
compatibility_date = "2026-03-12"
workers_dev = true

[vars]
TELEGRAM_CHAT_ID = "-1003546439681"
TG_THREAD_MEMBERSHIP = "20"
TG_THREAD_CONFIRM = "61"
TG_THREAD_POINTS = "17"
POINTS_RATE = "100"
AIRTABLE_BASE_ID = "appsV1ILPRfIjkaYg"
AIRTABLE_TABLE_PAYMENTS = "payments"
AIRTABLE_TABLE_POINTS_LEDGER = "points_ledger"
